theme: jekyll-theme-cayman
title: EarthCube RCN: "What About Model Data?": Determining Best Practices for Archiving and Reproducibility
author: dcschus
email: schuster@ucar.edu
description: > # this means to ignore newlines until "baseurl:"
  Information page for EarthCube RCN: "What About Model Data?": Determining Best Practices for Archiving and Reproducibility


show_excerpts: true # set to false to remove excerpts on the homepage
