theme: jekyll-theme-cayman
title: EarthCube RCN, "What About Model Data?" Determining Best Practices for Preservation and Replicability
author: dcschus
email: schuster@ucar.edu
description: > # this means to ignore newlines until "baseurl:"
  Project Information Website

show_excerpts: true # set to false to remove excerpts on the homepage
